"""Generate apps/observatory/src/birthPlaces.ts from Aliyun DataV GeoAtlas.

Data: areas_v3/bound/all.json — 民政部行政区划口径 (34 provinces / ~360 cities /
~2840 districts), each row carries adcode + name + GCJ-02 lng/lat. Coordinates are
converted to WGS-84 for astronomical time computation.

The legacy GeoNames builder lives at scripts/build_birth_places_geonames.py
(retired 2026-08-15: GeoNames aliases mixed 日文汉字/繁体/镇级名 and lacked a
city->county hierarchy).

Usage: .venv/Scripts/python.exe scripts/build_birth_areas.py
"""

from __future__ import annotations

import json
import math
import subprocess
import sys
from datetime import datetime, timezone, timedelta
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
ALL_JSON = ROOT / ".deploy-stage" / "datav_all.json"
OUT_TS = ROOT / "apps/observatory/src/birthPlaces.ts"
ALL_URL = "https://geo.datav.aliyun.com/areas_v3/bound/all.json"
COUNTRY = 100000


def ensure_source() -> None:
    if ALL_JSON.exists() and ALL_JSON.stat().st_size > 100_000:
        return
    ALL_JSON.parent.mkdir(parents=True, exist_ok=True)
    print("downloading", ALL_URL)
    subprocess.run(["curl", "-sSf", "--max-time", "60", ALL_URL, "-o", str(ALL_JSON)], check=True)


# --- GCJ-02 (高德/火星坐标) -> WGS-84, standard inverse approximation ---
_A = 6378245.0
_EE = 0.00669342162296594323


def _tlat(x: float, y: float) -> float:
    ret = -100.0 + 2.0 * x + 3.0 * y + 0.2 * y * y + 0.1 * x * y + 0.2 * math.sqrt(abs(x))
    ret += (20.0 * math.sin(6.0 * x * math.pi) + 20.0 * math.sin(2.0 * x * math.pi)) * 2.0 / 3.0
    ret += (20.0 * math.sin(y * math.pi) + 40.0 * math.sin(y / 3.0 * math.pi)) * 2.0 / 3.0
    ret += (160.0 * math.sin(y / 12.0 * math.pi) + 320.0 * math.sin(y * math.pi / 30.0)) * 2.0 / 3.0
    return ret


def _tlng(x: float, y: float) -> float:
    ret = 300.0 + x + 2.0 * y + 0.1 * x * x + 0.1 * x * y + 0.1 * math.sqrt(abs(x))
    ret += (20.0 * math.sin(6.0 * x * math.pi) + 20.0 * math.sin(2.0 * x * math.pi)) * 2.0 / 3.0
    ret += (20.0 * math.sin(x * math.pi) + 40.0 * math.sin(x / 3.0 * math.pi)) * 2.0 / 3.0
    ret += (150.0 * math.sin(x / 12.0 * math.pi) + 300.0 * math.sin(x / 30.0 * math.pi)) * 2.0 / 3.0
    return ret


def gcj02_to_wgs84(lng: float, lat: float) -> tuple[float, float]:
    if lng < 72.004 or lng > 137.8347 or lat < 0.8293 or lat > 55.8271:
        return round(lng, 6), round(lat, 6)
    dlat = _tlat(lng - 105.0, lat - 35.0)
    dlng = _tlng(lng - 105.0, lat - 35.0)
    radlat = lat / 180.0 * math.pi
    magic = math.sin(radlat)
    magic = 1 - _EE * magic * magic
    sqrtmagic = math.sqrt(magic)
    dlat = (dlat * 180.0) / ((_A * (1 - _EE)) / (magic * sqrtmagic) * math.pi)
    dlng = (dlng * 180.0) / (_A / sqrtmagic * math.cos(radlat) * math.pi)
    return round(lng - dlng, 6), round(lat - dlat, 6)


def dump(items: list, indent: int) -> str:
    pad = " " * indent
    parts = []
    for item in items:
        head = json.dumps(item[:4], ensure_ascii=False)
        if len(item) > 4:
            parts.append(f"{pad}{head[:-1]}, {dump(item[4], indent + 2)}]")
        else:
            parts.append(f"{pad}{head}")
    return "[\n" + ",\n".join(parts) + ",\n" + " " * (indent - 2) + "]"


def main() -> None:
    ensure_source()
    rows = json.loads(ALL_JSON.read_text(encoding="utf-8"))
    children: dict[int, list[dict]] = {}
    for row in rows:
        parent = row.get("parent")
        if parent is None:
            continue
        children.setdefault(int(parent), []).append(row)

    def node(row: dict) -> list:
        adcode = int(row["adcode"])
        lng, lat = gcj02_to_wgs84(float(row["lng"]), float(row["lat"]))
        kids = [node(k) for k in sorted(children.get(adcode, []), key=lambda r: r["adcode"])]
        base = [row["name"], str(adcode), lng, lat]
        return base + [kids] if kids else base

    provinces = [node(p) for p in sorted(children.get(COUNTRY, []), key=lambda r: r["adcode"])]

    counts = {"province": 0, "city": 0, "district": 0}

    def walk(items: list, depth: int) -> None:
        for item in items:
            key = {0: "province", 1: "city", 2: "district"}.get(depth, "district")
            counts[key] = counts.get(key, 0) + 1
            if len(item) > 4:
                walk(item[4], depth + 1)

    walk(provinces, 0)

    body = dump(provinces, 2)
    now = datetime.now(timezone(timedelta(hours=8))).strftime("%Y-%m-%dT%H:%M:%S+08:00")
    out = f"""/* eslint-disable */
// Generated by scripts/build_birth_areas.py — do not edit by hand.
// Source: Aliyun DataV GeoAtlas areas_v3 (民政部行政区划口径), coordinates GCJ-02 -> WGS-84.
// Snapshot {ALL_JSON.stat().st_size} bytes, built {now}. {counts['province']} provinces / {counts['city']} cities / {counts['district']} districts.

export type AreaNode = {{
  name: string
  adcode: string
  longitude: number
  latitude: number
  children: AreaNode[]
}}

// [name, adcode, longitude, latitude, children?]
type AreaRow = [string, string, number, number, AreaRow[]?]

const areaRows: AreaRow[] = {body}

function toNodes(rows: AreaRow[]): AreaNode[] {{
  return rows.map(([name, adcode, longitude, latitude, children]) => ({{
    name, adcode, longitude, latitude,
    children: children ? toNodes(children) : [],
  }}))
}}

export const birthAreas: AreaNode[] = toNodes(areaRows)

export function findArea(adcode: string, nodes: AreaNode[] = birthAreas): AreaNode | null {{
  for (const node of nodes) {{
    if (node.adcode === adcode) return node
    const hit = findArea(adcode, node.children)
    if (hit) return hit
  }}
  return null
}}

/** Return the sibling list (level) that directly contains adcode. */
export function findAreaLevel(adcode: string, nodes: AreaNode[] = birthAreas): AreaNode[] {{
  for (const node of nodes) {{
    if (node.adcode === adcode) return nodes
    if (node.children.some((child) => child.adcode === adcode)) return node.children
    const level = findAreaLevel(adcode, node.children)
    if (level.length) return level
  }}
  return []
}}

/** Return the chain from province down to adcode, e.g. [河北省, 石家庄市, 长安区]. */
export function findAreaPath(adcode: string, nodes: AreaNode[] = birthAreas, trail: AreaNode[] = []): AreaNode[] {{
  for (const node of nodes) {{
    const next = [...trail, node]
    if (node.adcode === adcode) return next
    const hit = findAreaPath(adcode, node.children, next)
    if (hit.length) return hit
  }}
  return []
}}

export const birthPlaceSource = {{
  name: 'Aliyun DataV GeoAtlas (areas_v3)',
  url: '{ALL_URL}',
  coordinateKind: 'WGS84 (converted from GCJ-02 representative point)',
  snapshotAt: '{now}',
  provinceCount: {counts['province']},
  cityCount: {counts['city']},
  districtCount: {counts['district']},
}} as const
"""
    OUT_TS.write_text(out, encoding="utf-8", newline="\n")
    print(f"wrote {OUT_TS} — {counts}, {OUT_TS.stat().st_size} bytes")


if __name__ == "__main__":
    try:
        main()
    except Exception as error:
        print(f"BUILD_FAILED: {error}", file=sys.stderr)
        raise
